### ISSUE TITLE
MongoError['No primary node is available!']

### ISSUE THREAD

**Issue by anil1712** [lashford/modern-web-template#6]
Hi, I am getting the exception while running the project, I am using play2.2.0. Please check the generated log by Typesafe console below. Please give me some solution for this.

--- (Running the application from SBT, auto-reloading is enabled) ---
[info] play - Listening for HTTP on /0.0.0.0:9000
(Server started, use Ctrl+D to stop and go back to the console...)
[1] warning javax.\* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
[info] application - ReactiveMongoPlugin starting...
[info] application - ReactiveMongoPlugin successfully started with db 'modern-web-template'! Servers:
[localhost:27017]
[info] play - Application started (Dev)
[DEBUG] [10/30/2014 09:32:13.168] [play-akka.actor.default-dispatcher-5] [EventStream(akka://reactivemongo)] logger log1-Logging$DefaultLogger started
[DEBUG] [10/30/2014 09:32:13.168] [play-akka.actor.default-dispatcher-5] [EventStream(akka://reactivemongo)] Default Loggers started
[error] r.api.Failover - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[na:na]
at reactivemongo.core.actors.MongoDBSystem$$anonfun$pickChannel$4.apply(actors.scala:508) ~[na:na]
at reactivemongo.core.actors.MongoDBSystem$$anonfun$pickChannel$4.apply(actors.scala:508) ~[na:na]
at scala.Option.getOrElse(Option.scala:120) ~[na:na]
at reactivemongo.core.actors.MongoDBSystem.pickChannel(actors.scala:508) ~[na:na]
at reactivemongo.core.actors.MongoDBSystem$$anonfun$receive$1.applyOrElse(actors.scala:252) ~[na:na]
[error] application -
! @6k39kii01 - Internal server error, for (GET) [/users] ->

**Comment by xu354cjo1008** [comment]
Hi,
I have same problem 
I am using play 2.2.1 built with Scala 2.10.2
please help

**Comment by RyanYao** [comment]
I have the same problem too.

**Comment by keepscoding** [comment]
you need to start the mongod

$ user@host /c/Program Files/MongoDB 2.6 Standard
$ ./bin/mongod --dbpath data

**Comment by lashford** [comment]
Hi Guys, yes as @keepscoding  pointed out you need to have a mongo instance running.  Going to close this.
